# Generated by Django 5.0 on 2026-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProejctsAndGallery',
            new_name='ProjectsAndGallery',
        ),
        migrations.AddField(
            model_name='category',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures'),
        ),
    ]
