# Generated by Django 5.0 on 2026-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0002_rename_proejctsandgallery_projectsandgallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('banner_type', models.CharField(choices=[('about', 'About'), ('services', 'Services'), ('gallery', 'Gallery'), ('contact', 'Contact')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
