# Generated by Django 5.0 on 2026-04-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0003_bannerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='banner_type',
            field=models.CharField(choices=[('about', 'About'), ('services', 'Services'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('parallax', 'Parallax')], max_length=100),
        ),
    ]
