# Generated by Django 5.0 on 2026-04-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0005_servicecategory_services_servicecategoryimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
