# Generated by Django 5.0 on 2026-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0006_rename_name_servicecategory_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='servicecategoryimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('category',), name='unique_main_image_per_category'),
        ),
    ]
