# Generated by Django 5.0 on 2026-04-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0008_aboutus_aboutuscontents_beforeandafter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorprofile',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
