# Generated by Django 5.0 on 2026-04-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0010_remove_aboutus_image_aboutusimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beforeandafter',
            old_name='image1',
            new_name='after',
        ),
        migrations.RenameField(
            model_name='beforeandafter',
            old_name='image2',
            new_name='before',
        ),
    ]
