# Generated by Django 5.0 on 2026-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divineApp', '0011_rename_image1_beforeandafter_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='banner_type',
            field=models.CharField(choices=[('about', 'About'), ('services', 'Services'), ('gallery', 'Gallery'), ('contact', 'Contact'), ('parallax', 'Parallax'), ('products', 'Products')], max_length=100),
        ),
    ]
